// AUTOGENERATED FILE: easyjson marshaler/unmarshalers.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD6888903DecodeGeneratorAppDomain(in *jlexer.Lexer, out *Target) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "target":
			out.AttributeName = string(in.String())
		case "attr_list":
			(out.Attributes).UnmarshalEasyJSON(in)
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD6888903EncodeGeneratorAppDomain(out *jwriter.Writer, in Target) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"target\":")
	out.String(string(in.AttributeName))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"attr_list\":")
	(in.Attributes).MarshalEasyJSON(out)
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Target) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD6888903EncodeGeneratorAppDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Target) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD6888903EncodeGeneratorAppDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Target) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD6888903DecodeGeneratorAppDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Target) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD6888903DecodeGeneratorAppDomain(l, v)
}
