// AUTOGENERATED FILE: easyjson marshaler/unmarshalers.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson43836510DecodeGeneratorAppDomain(in *jlexer.Lexer, out *TargetCollection) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(TargetCollection, 0, 1)
			} else {
				*out = TargetCollection{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Target
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson43836510EncodeGeneratorAppDomain(out *jwriter.Writer, in TargetCollection) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v TargetCollection) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson43836510EncodeGeneratorAppDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v TargetCollection) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson43836510EncodeGeneratorAppDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *TargetCollection) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson43836510DecodeGeneratorAppDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *TargetCollection) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson43836510DecodeGeneratorAppDomain(l, v)
}
