// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package domain

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonD6888903DecodeGeneratorAppDomain(in *jlexer.Lexer, out *Target) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "target":
			out.AttributeName = string(in.String())
		case "attr_list":
			if in.IsNull() {
				in.Skip()
				out.Attributes = nil
			} else {
				in.Delim('[')
				if !in.IsDelim(']') {
					out.Attributes = make(AttributeCollection, 0, 4)
				} else {
					out.Attributes = AttributeCollection{}
				}
				for !in.IsDelim(']') {
					var v1 Attribute
					v1 = Attribute(in.String())
					out.Attributes = append(out.Attributes, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonD6888903EncodeGeneratorAppDomain(out *jwriter.Writer, in Target) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"target\":")
	out.String(string(in.AttributeName))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"attr_list\":")
	if in.Attributes == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in.Attributes {
			if v2 > 0 {
				out.RawByte(',')
			}
			out.String(string(v3))
		}
		out.RawByte(']')
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Target) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonD6888903EncodeGeneratorAppDomain(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Target) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonD6888903EncodeGeneratorAppDomain(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Target) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonD6888903DecodeGeneratorAppDomain(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Target) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonD6888903DecodeGeneratorAppDomain(l, v)
}
